# SPDX-FileCopyrightText: 2023-2026 CoreWeave, Ltd
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: sunk-anywhere

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sunk-syncer
  namespace: tenant-slurm
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sunk-syncer
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 20s
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_part_of
          targetLabel: slurm_cluster
